implemented Events tests
PlayFab/PlayFabCoreCSdk_Template pull request #2
Opened 2021-12-02 02:33 UTC by tculotta

SharedGroups tests are temporarily broken since some cleanup relies on ...ServerDeleteGroup which is no longer included for the GDK

2021-12-02 02:38 UTC, tculotta commented on templates/Test.cpp.ejs
> +    struct <%- resultHolderType %> : public <%- prereqCall.resultDatatype.name %>Holder
This set of APIs uncovered occasional naming conflicts with certain result holder types

2021-12-02 02:40 UTC, tculotta commented on templates/TestLog.cpp.ejs
> +    if( datatype.name.includes(call.result) )
Some APIs share result types and the datatype naming differs only by Admin/Client/Server prefix

2021-12-03 18:27 UTC, jplafonta commented on customizations.json
> +      "ServerWriteTitleEvent": "Events"
did we confirm that these are APIs we will want to include in the SDK even if Admin/Server are generally excluded?  These server APIs use secret key auth which I thought we didn't want in the client SDK?

2021-12-03 18:29 UTC, jplafonta commented on source/test/TestApp/GDK/TestAppGDK.cpp
> +    titleDataFile.open("testTitleData.json", std::ios::binary | std::ios::in);
>testTitleData [](http://example.com/codeflow?start=24&length=13)

thanks for catching and fixing this

2021-12-03 18:30 UTC, jplafonta commented on make.js
> +// Used to insert if platform macros to exclude output per call
is this excluding output? or excluding tests entirely on certain platforms?

2021-12-03 18:30 UTC, jplafonta requested changes
:clock1:

2021-12-03 20:37 UTC, tculotta commented on make.js
> +// Used to insert if platform macros to exclude output per call
I'm excluding the tests themselves, not just output since the tests can't even use those APIs

2021-12-03 20:41 UTC, tculotta commented on customizations.json
> +      "ServerWriteTitleEvent": "Events"
I haven't seen anything about not including them in the SDK. Though I also haven't seen anything about keeping them in either

2021-12-03 23:14 UTC, jplafonta commented on customizations.json
> +      "ServerWriteTitleEvent": "Events"
Server and Admin are exluded (at least by default via preprocessor ifdefs, possibly always).  We should confirm that we want these APIs included before moving them to "Events"

2021-12-03 23:15 UTC, jplafonta commented on make.js
> +// Used to insert if platform macros to exclude output per call
Makes sense. Can you update this comment to make that a little clearer

2021-12-03 23:15 UTC, jplafonta approved these changes
:shipit:

2021-12-03 23:25 UTC, merged